set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=$HOME/vimfiles/bundle/Vundle.vim/
call vundle#begin('$USERPROFILE/vimfiles/bundle/')
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'Valloric/YouCompleteMe'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

syntax on
colorscheme anderson

set number

filetype plugin indent on 
" show existing tab with 4 spaces width
set tabstop=4
" when indentin with '>', use 4 spaces width
set shiftwidth=4
" on pressing tab, insert 4 spaces
set expandtab
set guifont=ProFontWindows:h10
set fileformats=unix,dos
set fileformat=unix
inoremap " ""<Left>
inoremap ' ''<Left>
inoremap ( ()<Left>
""inoremap <c-)> )
""inoremap ) <Left>
inoremap [ []<Left>
inoremap { {<CR><CR><Left><CR>}<UP><TAB>
command! SaveSession mksession! E:\Programs\Vim\vimfiles\sessions\session.vim
command! LoadSession so E:\Programs\Vim\vimfiles\sessions\session.vim
autocmd VimEnter * LoadSession
autocmd GUIEnter * simalt ~x
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=
call pathogen#infect() 
map <F2> :NERDTree %:p<CR>
map <F3> :tabnew<CR>
map <F4> :tabclose<CR>
map <F5> :!php -l %<CR><CR>
map <F6> :Flisttoggle<CR>

